title: "Les Vendredis"
description: "A handmade A-frame cabin and private garden in Sainte-Luce, Martinique."
url: "https://les-vendredis.casa"
baseurl: ""

permalink: /journal/:slug/

source: .
destination: _site
plugins:
  - jekyll-feed

collections:
  posts:
    output: true

liquid:
  error_mode: strict
