import { ImageItem } from './types';

export const IMAGES: ImageItem[] = [
  {
    id: '1',
    url: 'https://picsum.photos/seed/cabin-1/1200/800',
    title: 'The A-Frame Exterior',
    description: 'Sustainable wooden architecture nestled in the lush tropical forest of Martinique.',
    width: 1200,
    height: 800,
  },
  {
    id: '2',
    url: 'https://picsum.photos/seed/tropical-2/800/1200',
    title: 'Verdant Canopy',
    description: 'The view from the loft, looking out into the heart of the jungle.',
    width: 800,
    height: 1200,
  },
  {
    id: '3',
    url: 'https://picsum.photos/seed/wood-3/1200/1200',
    title: 'Artisanal Details',
    description: 'Hand-carved local timber used throughout the interior structure.',
    width: 1200,
    height: 1200,
  },
  {
    id: '4',
    url: 'https://picsum.photos/seed/beach-4/1200/800',
    title: 'Coastal Proximity',
    description: 'Just a short walk from the cabin to the pristine Caribbean shores.',
    width: 1200,
    height: 800,
  },
  {
    id: '5',
    url: 'https://picsum.photos/seed/sunset-5/800/1200',
    title: 'Golden Hour',
    description: 'Warm light filtering through the palm leaves at dusk.',
    width: 800,
    height: 1200,
  },
  {
    id: '6',
    url: 'https://picsum.photos/seed/interior-6/1200/800',
    title: 'Minimal Living',
    description: 'A space designed for peace, reflection, and connection with nature.',
    width: 1200,
    height: 800,
  },
  {
    id: '7',
    url: 'https://picsum.photos/seed/garden-7/1200/1200',
    title: 'Botanical Sanctuary',
    description: 'The private garden surrounding the A-Frame, filled with native flora.',
    width: 1200,
    height: 1200,
  },
  {
    id: '8',
    url: 'https://picsum.photos/seed/mist-8/1200/800',
    title: 'Morning Mist',
    description: 'The cabin emerging from the clouds on a humid tropical morning.',
    width: 1200,
    height: 800,
  },
  {
    id: '9',
    url: 'https://picsum.photos/seed/night-9/800/1200',
    title: 'Starlit Canopy',
    description: 'The architectural silhouette against the clear West Indies night sky.',
    width: 800,
    height: 1200,
  },
];
