import { ImageItem } from './types';

export const IMAGES: ImageItem[] = [
  {
    id: '1',
    url: '/images/IMG_0390.jpg',
    title: 'Verdant Canopy',
    description: 'The view from the loft, looking out into the heart of the jungle. April 2026',
    width: 900,
    height: 1200,
  },
  {
    id: '2',
    url: '/images/IMG_0391.jpg',
    title: 'Artisanal Details',
    description: 'Hand-carved local timber used throughout the interior structure. April 2026',
    width: 1200,
    height: 1600,
  },
  {
    id: '3',
    url: '/images/IMG_0392.jpg',
    title: 'Coastal Proximity',
    description: 'Just a short walk from the cabin to the pristine Caribbean shores. April 2026',
    width: 900,
    height: 1200,
  },
  {
    id: '4',
    url: '/images/IMG_0396.jpg',
    title: 'Golden Hour',
    description: 'Warm light filtering through the palm leaves at dusk. April 2026',
    width: 1200,
    height: 1600,
  },
  {
    id: '5',
    url: '/images/IMG_0387.jpg',
    title: 'The A-Frame Exterior',
    description: 'Sustainable wooden architecture nestled in the lush tropical forest of Martinique. April 2026',
    width: 1200,
    height: 1600,
  },
  {
    id: '6',
    url: '/images/IMG_3936.jpg',
    title: 'Wooden Frame',
    description: 'The structural beauty of locally sourced timber. October 2024',
    width: 1200,
    height: 800,
  },
  {
    id: '7',
    url: '/images/IMG_0896.jpg',
    title: 'Botanical Sanctuary',
    description: 'The private garden surrounding the A-Frame, filled with native flora. March 2025',
    width: 1200,
    height: 800,
  },
  {
    id: '8',
    url: '/images/IMG_0940.jpg',
    title: 'Morning Mist',
    description: 'The cabin emerging from the clouds on a humid tropical morning. March 2025',
    width: 1200,
    height: 800,
  },
  {
    id: '9',
    url: '/images/IMG_1251.jpg',
    title: 'Natural Light',
    description: 'Sunlight streaming through the architectural lines of the cabin. June 2025',
    width: 1200,
    height: 800,
  },
  {
    id: '10',
    url: '/images/IMG_1348.jpg',
    title: 'Forest Serenity',
    description: 'Surrounded by the tranquility of untouched tropical nature. June 2025',
    width: 1200,
    height: 800,
  },
  {
    id: '11',
    url: '/images/IMG_1355.jpg',
    title: 'Architectural Detail',
    description: 'The geometric precision of the A-Frame design against natural elements. June 2025',
    width: 1200,
    height: 800,
  },
  {
    id: '12',
    url: '/images/IMG_3290.jpg',
    title: 'Tropical Flora',
    description: 'The lush vegetation surrounding and embracing the structure. February 2026',
    width: 1200,
    height: 800,
  },
  {
    id: '13',
    url: '/images/IMG_3343.jpg',
    title: 'Sunset View',
    description: 'The cabin silhouetted against the Caribbean sunset. March 2026',
    width: 1200,
    height: 800,
  },
  {
    id: '14',
    url: '/images/AA4940C0-AE7D-4C3A-8304-688BF02A1955.jpg',
    title: 'Garden Path',
    description: 'The winding path leading through the botanical sanctuary. May 2024',
    width: 1200,
    height: 800,
  },
  {
    id: '15',
    url: '/images/IMG_STRUCTURE.jpg',
    title: 'Main Structure',
    description: 'The A-Frame structure taking shape with primary beams in place. April 2024',
    width: 1200,
    height: 900,
  },
  {
    id: '16',
    url: '/images/IMG_FRAMING.jpg',
    title: 'Framing Phase',
    description: 'The wooden frame assembly during construction. April 2024',
    width: 1200,
    height: 900,
  },
  {
    id: '17',
    url: '/images/IMG_CONSTRUCTION.jpg',
    title: 'Foundation Work',
    description: 'The foundation and earthwork during the building phase. July 2023',
    width: 1200,
    height: 900,
  },
  {
    id: '18',
    url: '/images/IMG_4621.JPG',
    title: 'Aerial View',
    description: 'A panoramic view from above the cabin and surrounding forest.',
    width: 1600,
    height: 1200,
  },
  {
    id: '19',
    url: '/images/IMG_4688.JPG',
    title: 'Mountain Backdrop',
    description: 'The A-Frame framed against the dramatic Martinique landscape.',
    width: 1600,
    height: 1200,
  },
];
