service: les-vendredis
image: bolom/les-vendredis

servers:
  web:
    - <%= ENV.fetch("KAMAL_INFOMANIAK_HOST", "replace-with-infomaniak-host") %>
  job:
    hosts:
      - <%= ENV.fetch("KAMAL_INFOMANIAK_HOST", "replace-with-infomaniak-host") %>
    cmd: bin/jobs

proxy:
  ssl: true
  host: lesvendredis.casa
  app_port: 80

registry:
  username: <%= ENV.fetch("KAMAL_REGISTRY_USER", "bolom") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    APP_HOST: lesvendredis.casa
    GA_MEASUREMENT_ID: G-HD3V7YWDWQ
    MAIL_FROM: hello@lesvendredis.casa
    MAIL_REPLY_TO: hello@lesvendredis.casa
    BOOKING_OWNER_EMAIL: hello@lesvendredis.casa
  secret:
    - DATABASE_URL
    - AIRBNB_ICAL_URL
    - BOOKING_ICAL_URL
    - RAILS_MASTER_KEY
    - RESEND_API_KEY
    - SECRET_KEY_BASE

volumes:
  - "les_vendredis_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  context: ..
  dockerfile: web/Dockerfile
